version: "2"

services:
  remark:
    image: umputun/remark42:latest
    container_name: "remark42"
    hostname: "remark42"
    restart: always

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    # uncomment to expose directly (no proxy)
    ports:
      - "9090:8080"

    environment:
      - REMARK_URL=https://remark.maxvamp.com
      - SECRET=S09cNvJ6Xcl5lfCt7jP0
      - SITE=vampstories
      - DEBUG=true
      - EMOJI=true
      - AUTH_ANON=true
      - ANON_VOTE=true
      - VOTES_IP=true

    volumes:
      - ./var:/srv/var